In [1]:
# This is from the PyTorch Blitz Training
# https://pytorch.org/tutorials/beginner/deep_learning_60min_blitz.html

In [27]:
import numpy as np
import torch
torch.cuda.is_available()

True

## Some Basics

### Making Tensors

In [4]:
# make an empty matrix
x = torch.empty(5,3)
print(x)

tensor([[0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.0000, 0.0000, 0.0000]])


In [6]:
# create a randomly generated matix
x = torch.rand(5,3)
print(x)

tensor([[0.0804, 0.3238, 0.4473],
        [0.7145, 0.6335, 0.6027],
        [0.2589, 0.4957, 0.4775],
        [0.3231, 0.0513, 0.3294],
        [0.0930, 0.0837, 0.1560]])


In [8]:
# create a matrix of zero of type long
x = torch.zeros(5,3, dtype = torch.long)
print(x)

tensor([[0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0],
        [0, 0, 0]])


In [9]:
# create a tensor from data
x = torch.tensor([5.5,3])
print(x)

tensor([5.5000, 3.0000])


In [11]:
# create tensor from existing tensor
x = x.new_ones(5, 3, dtype = torch.double)
x = torch.randn_like(x, dtype=torch.float)
print(x)

tensor([[ 1.4378,  0.6958,  0.7730],
        [-0.4763, -0.8928, -0.4699],
        [ 2.2479,  0.1121,  0.1123],
        [-0.0879, -1.2663, -1.0145],
        [ 0.2286, -0.5894, -0.1122]])


In [12]:
# get tensor size
print(x.size())

torch.Size([5, 3])


### Operations

In [13]:
# Addition

# style 1
y = torch.rand(5, 3)
print(x + y)
# style 2
print(torch.add(x,y))

tensor([[ 2.0035,  0.7774,  1.6357],
        [-0.0966, -0.7646,  0.3077],
        [ 2.8013,  0.3365,  0.8439],
        [ 0.6270, -0.8057, -0.7173],
        [ 1.2087,  0.0902,  0.0460]])
tensor([[ 2.0035,  0.7774,  1.6357],
        [-0.0966, -0.7646,  0.3077],
        [ 2.8013,  0.3365,  0.8439],
        [ 0.6270, -0.8057, -0.7173],
        [ 1.2087,  0.0902,  0.0460]])


In [15]:
# Addition with a Tensor as output
result = torch.empty(5, 3)
torch.add(x, y, out=result)
print(result)

tensor([[ 2.0035,  0.7774,  1.6357],
        [-0.0966, -0.7646,  0.3077],
        [ 2.8013,  0.3365,  0.8439],
        [ 0.6270, -0.8057, -0.7173],
        [ 1.2087,  0.0902,  0.0460]])


In [16]:
# inplace add
y.add_(x)
print(y)

tensor([[ 2.0035,  0.7774,  1.6357],
        [-0.0966, -0.7646,  0.3077],
        [ 2.8013,  0.3365,  0.8439],
        [ 0.6270, -0.8057, -0.7173],
        [ 1.2087,  0.0902,  0.0460]])


In [17]:
# numpy like slicing
print(x[:,1])

tensor([ 0.6958, -0.8928,  0.1121, -1.2663, -0.5894])


In [18]:
# resize tensors
x = torch.randn(4, 4)
y = x.view(16)
z = x.view(-1,8) # -1 infers from other dimensions
print(x.size(), y.size(), z.size())

torch.Size([4, 4]) torch.Size([16]) torch.Size([2, 8])


In [20]:
# extract single valued tensors
x = torch.randn(1)
print(x)
print(x.item())

tensor([-0.8406])
-0.8406229615211487


### The Bridge to NumPy

In [23]:
a = torch.ones(5)
print(a)

tensor([1., 1., 1., 1., 1.])


In [25]:
# to numpy
b = a.numpy()
print(b)

[1. 1. 1. 1. 1.]


In [26]:
a.add_(1)
print(a)
print(b)

tensor([2., 2., 2., 2., 2.])
[2. 2. 2. 2. 2.]


In [28]:
# from numpy
a = np.ones(5)
b = torch.from_numpy(a)
np.add(a, 1, out=a)
print(a)
print(b)

[2. 2. 2. 2. 2.]
tensor([2., 2., 2., 2., 2.], dtype=torch.float64)


In [31]:
device = torch.device("cuda")
y = torch.ones_like(x, device = device)
x = x.to(device)
z = x + y
print(z)
print(z.to("cpu", torch.double))

tensor([0.1594], device='cuda:0')
tensor([0.1594], dtype=torch.float64)
